In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as py

In [3]:
data = pd.read_csv("Nigerian_Graduates_Destination_Survey_(2013 -2017)_(Responses).csv")

In [4]:
data.head()

,Timestamp,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?",...,What currency are you currently paid in?,Approximately how many hours a day do you currently work?,"As far as you are aware, what was most important to your current employer about your qualification?",How do you find out about your job(s)?,"Thinking about your current employment, did you work for your employer before or during your higher education study?",Which form of transport do you use the most?,Were you able to rent an apartment or buy a car from the salary you got from your first job?,My course of study prepared me well for employment,My course of study prepared me well for further studies,Which of these skills/knowledge did your higher education prepare you for?
0,2/8/2018 9:05:23,Male,2013,Electrical & Electronic Engineering,"Obafemi Awolowo University,Ile-Ife",Bachelor's degree,Working full time (paid employment),3,NaN,NaN,...,Naira,8.0,No one thing was important,Internship,No,Bus,Yes: From my first job,No,No,"Critical thinking skills, Ability to solve com..."
1,2/15/2018 12:11:32,Male,2014,Psychology,"Obafemi Awolowo University,Ile-Ife",Bachelor's degree,Working full time (paid employment),2,Yes,2017.0,...,Naira,8.0,IT/SIWES/Internship experience (gained as part...,Internship,No,BRT,No: From my current job,Strongly Disagree,Agree,"Critical thinking skills, Ability to solve com..."
2,2/15/2018 13:47:10,Female,2013,Economics,"Bells University of Technology, Otta",Bachelor's degree,Working full time (paid employment),2,Yes,NaN,...,Naira,14.0,The subject(s) I studied,Employer's website,No,Uber/Taxify/Taxi services,No: From my current job,Disagree,Agree,"Ability to work with others, Written communica..."
3,2/16/2018 13:01:34,Male,2017,Mass Communication (Communication and Language...,"Bowen University, Iwo",Master's degree,Self-employed/freelance/entrepreneur,0,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2/16/2018 13:18:03,Female,2013,Statistics,Ekiti State University,Bachelor's degree,Working full time (paid employment),3,Yes,2016.0,...,Naira,8.0,IT/SIWES/Internship experience (gained as part...,"Personal contacts, including family and friends",No,Commercial Vehicles,No,Agree,Agree,Critical thinking skills

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5219 entries, 0 to 5218
Data columns (total 36 columns):
 #   Column                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                        --------------  -----
 0   Timestamp                                                                                                                     5219 non-null   object
 1   What is your gender                                                                                                           5219 non-null   object
 2   Year of graduation                                                                                                            5219 non-null   int64
 3   Title of course studied                                                                                                       5219 non-null   object
 4   Polytechnic/University attended                                                                                               5219 non-null   object
 5   What is your highest level of education?                                                                                      5219 non-null   object
 6   What best describes your current status?                                                                                      5219 non-null   object
 7   How many jobs have you had since graduation including your current one?                                                       5219 non-null   int64
 8   Have you completed your NYSC?                                                                                                 5218 non-null   object
 9   If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?                     4278 non-null   float64
 10  Did you get your first full time job through your NYSC placement?                                                             5218 non-null   object
 11  Thinking about your first employment after graduation, what was your job level?                                               1656 non-null   object
 12  What is/was your job role?                                                                                                    1654 non-null   object
 13  What sector/industry is your company in? (E.g. Banking, Agriculture, Telecommunication)                                       1656 non-null   object
 14  Still thinking about your first employment, what is/was your monthly income level?                                            1656 non-null   object
 15  Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?  1656 non-null   object
 16  What was the most significant reason for deciding to take your first job?                                                     1656 non-null   object
 17  Thinking about your current employment, what is your job level?                                                               3432 non-null   object
 18  What is your job role?                                                                                                        3431 non-null   object
 19  What sector/industry is your company in? (E.g. Banking, Agriculture, Telecommunication).1                                     3432 non-null   object
 20  What is your current monthly income level?                                                                                    3432 non-null   object
 21  Did you need your higher education qualification to get this job (the actual qualification, not the subject of study)?        3431 non-null   object
 22  What was the most significant reason for deciding to take this job?                                                           3432 non-null   object
 23  Which employer in the country do you think offers the best opportunities for graduates?                                       2958 non-null   object
 24  Reason why?                                                                                                                   3109 non-null   object
 25  Which sector is your most preferred sector to work in?                                                                        3297 non-null   object
 26  What currency are you currently paid in?                                                                                      3432 non-null   object
 27  Approximately how many hours a day do you currently work?                                                                     3432 non-null   float64
 28  As far as you are aware, what was most important to your current employer about your qualification?                           3432 non-null   object
 29  How do you find out about your job(s)?                                                                                        3432 non-null   object
 30  Thinking about your current employment, did you work for your employer before or during your  higher education study?         3432 non-null   object
 31  Which form of transport do you use the most?                                                                                  3432 non-null   object
 32  Were you able to rent an apartment or buy a car from the salary you got from your first job?                                  3432 non-null   object
 33  My course of study prepared me well for employment                                                                            3432 non-null   object
 34  My course of study prepared me well for further studies                                                                       3432 non-null   object
 35  Which of these skills/knowledge did your higher education prepare you for?                                                    3432 non-null   object
dtypes: float64(2), int64(2), object(32)
memory usage: 1.4+ MB

1,2,3,4,5,6,7,8,9,15,33

In [20]:
# create a list of the important features

columns = ["What is your gender","Year of graduation", "Title of course studied",
           "Polytechnic/University attended","What is your highest level of education?",
          "What best describes your current status?", "How many jobs have you had since graduation including your current one?",
          "Have you completed your NYSC?",
           "If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?",
          "Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",
          "My course of study prepared me well for employment"]

In [21]:
new_data = data.loc[:, columns] #create the new dataframe with the important features

In [22]:
# new dataframe we're working with

new_data

,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?","Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",My course of study prepared me well for employment
0,Male,2013,Electrical & Electronic Engineering,"Obafemi Awolowo University,Ile-Ife",Bachelor's degree,Working full time (paid employment),3,NaN,NaN,No: the qualification was not required,No
1,Male,2014,Psychology,"Obafemi Awolowo University,Ile-Ife",Bachelor's degree,Working full time (paid employment),2,Yes,2017.0,Yes: the qualification was a formal requirement,Strongly Disagree
2,Female,2013,Economics,"Bells University of Technology, Otta",Bachelor's degree,Working full time (paid employment),2,Yes,NaN,Yes: the qualification was a formal requirement,Disagree
3,Male,2017,Mass Communication (Communication and Language...,"Bowen University, Iwo",Master's degree,Self-employed/freelance/entrepreneur,0,Yes,NaN,NaN,NaN
4,Female,2013,Statistics,Ekiti State University,Bachelor's degree,Working full time (paid employment),3,Yes,2016.0,Yes: while the qualification was not a formal ...,Agree
...,...,...,...,...,...,...,...,...,...,...,...
5214,Female,2014,Physics and Astronomy,University of Lagos,Bachelor's degree,Unemployed,1,Yes,2016.0,NaN,Strongly Agree
5215,Female,2017,Acturial Science,University of Lagos,Bachelor's degree,Youth Corper (NYSC),0,No,NaN,NaN,NaN
5216,Female,2014,Political Science,Others (For foreign trained students),Bachelor's degree,Working full time (paid employment),1,Yes,2015.0,NaN,Disagree
5217,Female,2015,Business Administration,"The Polytechnic Ibadan, Ibadab, Oyo State.",Higher National Diploma (HND),Self-employed/freelance/entrepreneur,2,Yes,2017.0,Yes: the qualification was a formal requirement,Agree
5218,Male,2016,Economics,Usumanu Danfodiyo University,Bachelor's degree,Unemployed,0,Yes,2018.0,NaN,NaN

# data cleaning

In [30]:
new_data.describe(include = "all")

,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?","Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",My course of study prepared me well for employment
count,5219,5219.000000,5219,5219,5219,5219,5219.000000,5218,4278.000000,1656,3432
unique,3,NaN,127,158,6,10,NaN,3,NaN,4,5
top,Male,NaN,Computer Science,University of Lagos,Bachelor's degree,Working full time (paid employment),NaN,Yes,NaN,Yes: the qualification was a formal requirement,Agree
freq,2624,NaN,459,527,4402,1371,NaN,3418,NaN,885,1574
mean,NaN,2015.329182,NaN,NaN,NaN,NaN,1.136999,NaN,2016.579009,NaN,NaN
std,NaN,1.305153,NaN,NaN,NaN,NaN,1.140146,NaN,1.354837,NaN,NaN
min,NaN,2013.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2013.000000,NaN,NaN
25%,NaN,2014.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2016.000000,NaN,NaN
50%,NaN,2015.000000,NaN,NaN,NaN,NaN,1.000000,NaN,2017.000000,NaN,NaN
75%,NaN,2016.000000,NaN,NaN,NaN,NaN,2.000000,NaN,2017.000000,NaN,NaN
max,NaN,2017.000000,NaN,NaN,NaN,NaN,10.000000,NaN,2019.000000,NaN,NaN

### gender column

In [36]:
new_data["What is your gender"].value_counts()  # 3 wrong data on the "gender" column

Male                 2624
Female               2592
Prefer not to say       3
Name: What is your gender, dtype: int64

In [39]:
new_data["What is your gender"].isna().sum() #no missing values

0

### Year of graduation

In [40]:
new_data["Year of graduation"].value_counts() #no wrong data

2015    1327
2017    1259
2016    1214
2014     824
2013     595
Name: Year of graduation, dtype: int64

In [41]:
new_data["Year of graduation"].isna().sum()  #no missing value

0

### Title of course studied

In [52]:
new_data["Title of course studied"].value_counts()

Computer Science                                        459
Accountancy                                             373
Economics                                               321
Electrical & Electronic Engineering                     214
Mass Communication (Communication and Language Arts)    204
                                                       ...
Music                                                     1
Department of Pharmacology and Toxicology                 1
Child Dental Health                                       1
Archeology and Tourism                                    1
Igbo Linguistics                                          1
Name: Title of course studied, Length: 127, dtype: int64

In [53]:
new_data["Title of course studied"].isna().sum()  #no missing value

0

### Polytechnic/University attended

In [56]:
new_data["Polytechnic/University attended"].unique()

array(['Obafemi Awolowo University,Ile-Ife',
       'Bells University of Technology, Otta', 'Bowen University, Iwo',
       'Ekiti State University', 'University of Benin',
       'Covenant University Ota', 'University of Lagos',
       'University of Ibadan', 'University of Port-Harcourt',
       'Babcock University,Ilishan-Remo',
       'Yaba College of Technology, Yaba, Lagos State.',
       'University of Abuja, Gwagwalada',
       'Federal University of Technology, Akure',
       'Kwara State Polytechnic, Ilorin, Kwara State.',
       'Crawford University Igbesa',
       'Federal University of Technology, Minna.',
       'Lagos State University Ojo, Lagos.',
       'Heritage Polytechnic, Ikot Udota, Eket, Akwa Ibom State',
       'Federal University, Oye-Ekiti, Ekiti State',
       'University of Nigeria, Nsukka',
       'Rivers State University of Science & Technology',
       'Ambrose Alli University, Ekpoma,',
       'Ladoke Akintola University of Technology, Ogbomoso',
       'Federal University of Technology, Owerri',
       'Caleb University, Lagos', 'Adekunle Ajasin University, Akungba.',
       'University of Ilorin',
       'Federal Polytechnic Kaura Namoda, Zamfara State.',
       'Madonna University, Okija',
       'Modibbo Adama University of Technology, Yola',
       'University of Maiduguri',
       'National Open University of Nigeria, Lagos.',
       'Abia State University, Uturu.', 'University of Uyo',
       'Olabisi Onabanjo University Ago-Iwoye',
       'Anambra State University of Science & Technology, Uli',
       'Federal Polytechnic Ado Ekiti, Ekiti State.',
       'Delta State University Abraka',
       'Federal Polytechnic Nekede, Owerri, Imo State.',
       "Redeemer's University, Mowe", 'Osun State University, Oshogbo',
       'Imo State University, Owerri',
       'Benue State Polytechnic, Ugbokolo, Benue State.',
       'Tai Solarin Univ. of Education, Ijebu-Ode',
       'University of Agriculture, Abeokuta.',
       'Lagos State Polytechnic, Ikorodu, Ikeja, Lagos, Lagos State.',
       'Plateau State Polytechnic, Barkin-Ladi, Jos, Plateau State.',
       'Abubakar Tafawa Balewa University, Bauchi',
       'University of Calabar',
       'The Polytechnic Ibadan, Ibadab, Oyo State.',
       'Ebonyi State University, Abakaliki',
       'Bingham University, New Karu', 'Nnamdi Azikiwe University, Awka',
       'Nigerian-Turkish Nile University, Abuja',
       'Institute of Management and Technology, Enugu, Enugu State.',
       'Landmark University,Omu-Aran.',
       'Akwa Ibom State Polytechnic, Ikot Osurua, Ikot -Ekpene, Akwa Ibom State.',
       'Bayero University,Kano',
       'Moshood Abiola Polytechnic, Abeokuta, Ogun State.',
       'University of Agriculture, Makurdi.',
       'Benue State University, Makurdi.',
       'Michael Okpara Uni. of Agric., Umudike',
       'Kogi State University Anyigba', 'Kaduna State University, Kaduna',
       'D.S. Adegbenro ICT Polytechnic, Itori-Ewekoro, Ifo, Ogun State.',
       'Federal Polytechnic Offa, Kwara State.', 'University of Jos',
       'Crescent University,', 'Wesley Univ. of Science & Tech.,Ondo',
       'Others (For foreign trained students)',
       'Ahmadu Bello University, Zaria', 'Caritas University, Enugu',
       'Veritas University', 'Oduduwa University, Ipetumodu - Osun State',
       'Al-Hikmah University, Ilorin', 'Kwara State University, Ilorin',
       'Igbinedion University Okada', 'Fountain Unveristy,Oshogbo',
       'Ignatius Ajuru University of Education,Rumuolumeni.',
       'Akwa Ibom State University of Technology, Uyo',
       'Enugu State University of Science and Technology, Enugu',
       'Federal University, Lafia, Nasarawa State',
       'Lead City University, Ibadan', 'Usumanu Danfodiyo University',
       'Joseph Ayo Babalola University, Ikeji-Arakeji',
       'Rufus Giwa Polytechnic, Owo, Owo Ondo State.',
       'Auchi Polytechnic, Auchi, Edo State.',
       'Afe Babalola University, Ado-Ekiti - Ekiti State',
       'Abdu Gusau Polytechnic, Talata Mafara, Zamfara State.',
       'Federal University, Lokoja, Kogi State',
       'Federal Polytechnic Ilaro, Ogun State.',
       'Ogun State Institute of Technology, Igbesa Oba Adesola Market Road, Igbesa, Ogun State.',
       'Ajayi Crowther University, Ibadan',
       'American University of Nigeria, Yola',
       'Delta State Polytechnic, Ogwashi-Uku, Delta State.',
       'Osun State College of Technology, Esa â€“ Oke, Osun State.',
       'Niger Delta Unversity, Yenagoa',
       'Cross River State University of Science &Technology, Calabar',
       'The Polytechnic, Ile Ife, O.A.U. Ile-Ife, Osun State.',
       'Wellspring University, Evbuobanosa - Edo State',
       'Kano University of Science & Technology, Wudil',
       'Allover Central Polytechnic, Sango Ota, Plot 3A & B Abiodun Popoola Street, Sango Ota, Ogun State.',
       'Nasarawa State University, Keffi',
       'Pan-African University, Lagos',
       'Federal Polytechnic Ede, Osun State.',
       'Benson Idahosa University,Benin City',
       'Gregory University, Uturu',
       'Grace Polytechnic, Surulere, Lagos State.',
       'Petroleum Training Institute Effurun, Delta State.',
       'Gateway Polytechnic, Saapade Prof. Wole Soyinka Way, Saapade Estate, Isara Ode-Remo, Ogun State.',
       'Imo State Polytechnic, Umuagwo, Ohaji, P.M.B. 1472, Umuagwo, Ohaji Owerri, Imo State',
       'Federal Polytechnic Bida, Niger State.',
       'Federal University of Petroleum Resources, Effurun',
       'Umaru Ali Shinkafi Polytechnic, Sokoto, Sokoto State.',
       'Others (For other Nigerian institutions not listed)',
       'Abubakar Tatari Ali Polytechnic, Jos Rd, Bauchi, Bauchi State.',
       'Adeleke University,Ede.', 'Adamawa State University Mubi',
       'Kogi State Polytechnic, Lokoja, Kogi State.',
       'Achievers University, Owo',
       'Delta State Polytechnic, Ozoro, Delta State.',
       'Federal Polytechnic Oko, Anambra State.',
       'Federal Polytechnic Idah, Kogi State.',
       'Delta State Polytechnic, Otefe-Oghara, Delta State',
       'Ibrahim Badamasi Babangida University, Lapai',
       'Federal University, Wukari, Taraba State',
       'Salem University,Lokoja',
       'Osun State Polytechnic, Iree, Osun State.',
       'Tansian University,Umunya',
       'Abia State Polytechnic, Aba, Abia State.',
       'Niger State Polytechnic, Zungeru, Niger State.',
       'Jigawa State Polytechnic, Dutse, Block 40-42, Old Secretariat, Dutse, Jigawa State.',
       'Gombe State Univeristy, Gombe',
       'Lagos City Polytechnic, Ikeja, Lagos State.',
       'Akanu Ibiam Federal Polytechnic Unwana, Afikpo, Ebonyi State.',
       'Federal Polytechnic Nasarawa, Nasarawa State.',
       'Federal University, Otuoke, Bayelsa',
       "Umaru Musa Yar'Adua University, Katsina",
       'Novena University, Ogume',
       'Federal Polytechnic Mubi, Adamawa State.',
       'Kebbi State University, Kebbi',
       'Federal Polytechnic Ile-Oluji, Ondo State',
       'Abraham Adesanya Polytechnic, Dogbolu/Akanran Ibadan Road, Atikori, Ijebu Igbo, Ogun State.',
       'Airforce Institute of Technology (AFIT), NAF Base Kaduna',
       'Federal University, Kashere, Gombe State',
       'Nuhu Bamalli Polytechnic, Zaria, Kaduna State.',
       'Ondo State University of Science & Technology, Okitipupa',
       'Our Saviour Institute of Science, Agriculture & Technology, Enugu, Enugu State.',
       'Taraba State University, Jalingo', 'Renaissance University,Enugu',
       'Dorben Polytechnic, Abuja, Garki, Bwari, Abuja.',
       'Ronik Polytechnic, Ejigbo, Ikeja, Lagos, Lagos State.',
       'Bolmor Polytechnic, Dugbe, Ibadan, Oyo State.',
       'Ibadan City Polytechnic, Alakia-Isebo/Iyana Church Road, Ibadan, Oyo State.',
       'Sokoto State University, Sokoto', 'Kaduna Polytechnic, Kaduna.',
       'Delta State Polytechnic, Ozoro',
       'Nasarawa State Polytechnic, Lafia, Nasarawa State.'], dtype=object)